### ISSUE TITLE
Link Javadoc for API Documentation

### ISSUE THREAD

**Issue by abhishektiwari** [muellerj2/netroles#33]
Although software is documented to a satisfactory level, for a Java package API documentation is scattered between `DESIGN.md` and `USAGE.md` and not very structured. Using an API documentation generator like Javadoc or something similar is strongly recommended. It seems you already using Javadoc comments, so it should be easier to generate. Or maybe you are generating Javadoc but not published it yet. 

[JOSS Review](https://github.com/openjournals/joss-reviews/issues/5903)

Update:
See comments below.

**Comment by abhishektiwari** [comment]
Given project released to [Maven Central](https://search.maven.org/) then your Javadoc is available at [javadoc.io](http://www.javadoc.io/) automatically. Can you link your Documentation/README page the javadoc.io?

https://www.javadoc.io/doc/io.github.muellerj2/netroles-api/latest/index.html
https://www.javadoc.io/doc/io.github.muellerj2/netroles-engine/latest/index.html
https://www.javadoc.io/doc/io.github.muellerj2/netroles-io-api/latest/index.html
https://www.javadoc.io/doc/io.github.muellerj2/netroles-io-engine/latest/index.html
https://www.javadoc.io/doc/io.github.muellerj2/netroles-lang-api/latest/index.html
https://www.javadoc.io/doc/io.github.muellerj2/netroles-networks-engine/latest/index.html
https://www.javadoc.io/doc/io.github.muellerj2/netroles-networks-api/latest/index.html

You can also generate Javadoc badges like

[![javadoc](https://javadoc.io/badge2/io.github.muellerj2/netroles-networks-engine/javadoc.svg)](https://javadoc.io/doc/io.github.muellerj2/netroles-networks-engine)

**Comment by leifeld** [comment]
I second this. I would either link to the Maven docs or your own generated javadoc in the Markdown files here in the repo.

**Comment by muellerj2** [comment]
I'm not a fan of linking to an external website I have no relation with, so let me try first make an attempt to set up a Github action that automatically deploys the Javadoc to muellerj2.github.io/netroles whenever a new release tag is created.

> Although software is documented to a satisfactory level, for a Java package API documentation is scattered between DESIGN.md and USAGE.md and not very structured. 

I agree that Javadoc is helpful, which is why it's available on Maven Central. My experience is that Javadoc is very helpful to find out details of the code, e.g., if you are looking for a specific functionality in a class or package, as long as one is already somewhat familiar with the structure of the library. However, I find it hard to understand the overall system implemented in a library just from the Javadoc. These other two files were added for this latter purpose. Unfortunately, there does not really seem to be a standard way to make available this kind of documentation: different Java libraries do different things.

**Comment by muellerj2** [comment]
I made a few improvements to the Javadoc documentation. I extended the Javadoc descriptions of some classes and packages, adding code examples or giving some higher-level explanations of the package contents.

These changes made the package overview section in the DESIGN.md basically superfluous. Besides, it's likely that I would forget to update this section to reflect future changes. That's why I have removed this section from the document.

Another minor change is that the generated Javadoc in the next release will add links to https://docs.oracle.com/javase/8/docs/api/ for JDK classes.

Regarding the main request of this issue: In the end, I decided to not host the Javadoc on GitHub pages (for now) but to link to javadoc.io as suggested. PR #45 adds a section in README.md that links to javadoc.io for all library modules. I did not add the badges, because I think eight badges saying "javadoc" next to each other is more confusing than helpful. When I added this section, I also reordered and reworded the sections referencing USAGE.md and DESIGN.md in the readme.

You can view the branch of PR #45 with the updated readme here: https://github.com/muellerj2/netroles/tree/link-javadoc-in-readme . Please tell me if you have further suggestions for improvement. If not, I will merge the PR as-is, closing this issue.

**Comment by abhishektiwari** [comment]
Thanks, you can mark this resolved now.
